---
- hosts: durga
  become: yes
  tasks:
 
    - name: create a file index.html
      file:
        path: /var/www/html/index.html
        state: touch
   
    - name: adding lines to index.html
      blockinfile:
        path: /var/www/html/index.html
        marker: "<!-- {mark} ANSIBLE MANAGED BLOCK -->"
        block: " this is test for adding a line useing ansible "

